version: "2"
services:
  portainer:
    image: portainer/portainer:latest
    container_name: portainer
    ports:
      - 8000:8000
      - 9000:9000
    volumes:
      - /mnt/docker/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
