version: "2"
services:
  transmission2:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=107
      - PGID=113
      - TZ=America/Vancouver
      - TRANSMISSION_WEB_HOME=/transmission-web-control/
    volumes:
      - /mnt/docker/transmission/config:/config
      - /mnt/torrent:/downloads
      - /mnt/torrent/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
